sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "1234"

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tQ9kUWViqvFpLV767KB
    access-key-secret: UsZ5UaHhvBEpUSsRs67prdTyxsSh1e
    bucket-name: take-out-images

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wxfc3c3644442bd85c
    secret: abb7887697d4a90c14518219278f8809
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://6bd3aa5b.r22.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://6bd3aa5b.r22.cpolar.top/notify/refundSuccess
